services:
  - type: web
    name: math-pot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_CONNECTOR
        sync: false
      - key: SESSION_KEY
        generateValue: true
      - key: COOKIE_KEY
        generateValue: true
